### ISSUE TITLE
Simplify success/failure check

### ISSUE THREAD

**Issue by marlonpp** [jmeas/react-request#126]
Would be great if we could simplify fetch `success/failure` check.
```javacript 
...     
(error || (response && !response.ok))
...
```
and it gets messy when there are multiple requests.

**Comment by jmeas** [comment]
Great idea :+1:

**Comment by jmeas** [comment]
I think I'll add a `failed` Boolean to go along with `fetching`.

**Comment by jmeas** [comment]
Resolved in #129 ; will be released as 2.0.0
